# Generated by Django 4.1.2 on 2022-10-06 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cpf", models.CharField(max_length=11)),
                ("cartão", models.CharField(max_length=12)),
                ("hora", models.TimeField()),
                ("dono_da_loja", models.CharField(max_length=127)),
                ("nome_da_loja", models.CharField(max_length=127)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="transactions.transation",
                    ),
                ),
            ],
        ),
    ]
