# Generated by Django 4.1.2 on 2022-10-06 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.SmallIntegerField()),
                ("descrição", models.CharField(max_length=127)),
                ("natureza", models.CharField(max_length=127)),
                ("sinal", models.IntegerField()),
            ],
        ),
    ]
